<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Modele log-liniowe – Wielowymiarowa analiza danych</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./correspondence.html" rel="prev">
<link href="./images/cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6b8c1b7f874bdd152064db223e7d36ae.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-7becdd8e1b79f26ea566d6ea537c1a09.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-6b8c1b7f874bdd152064db223e7d36ae.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Brak wyników",
    "search-matching-documents-text": "dopasowane dokumenty",
    "search-copy-link-title": "Kopiuj link do wyszukiwania",
    "search-hide-matches-text": "Ukryj dodatkowe dopasowania",
    "search-more-match-text": "więcej dopasowań w tym dokumencie",
    "search-more-matches-text": "więcej dopasowań w tym dokumencie",
    "search-clear-button-title": "Wyczyść",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Anuluj",
    "search-submit-button-title": "Zatwierdź",
    "search-label": "Szukaj"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./loglinear.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modele log-liniowe</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Przełącz pasek boczny" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Szukaj" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/logo.jpg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none"><img src="./images/logo.jpg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none"></a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Wielowymiarowa analiza danych</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/DariuszMajerek/WAD_new" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="https://twitter.com/intent/tweet?url=%7Curl%7C" title="Twitter" class="quarto-navigation-tool px-1" aria-label="Twitter"><i class="bi bi-twitter"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Przełącz tryb ciemny"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Przełącz tryb czytnika">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Szukaj"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wstęp</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Testy wielowymiarowe</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Analiza kanoniczna</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Analiza czynnikowa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modele strukturalne</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Metody redukcji wymiarowości</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Analiza skupień</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correspondence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analiza korespondencji</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loglinear.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modele log-liniowe</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatura</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Spis treści</h2>
   
  <ul>
<li><a href="#rys-historyczny" id="toc-rys-historyczny" class="nav-link active" data-scroll-target="#rys-historyczny">Rys historyczny</a></li>
  <li><a href="#cel" id="toc-cel" class="nav-link" data-scroll-target="#cel">Cel</a></li>
  <li><a href="#definicja-modelu" id="toc-definicja-modelu" class="nav-link" data-scroll-target="#definicja-modelu">Definicja modelu</a></li>
  <li>
<a href="#struktura-hierarchiczna" id="toc-struktura-hierarchiczna" class="nav-link" data-scroll-target="#struktura-hierarchiczna">Struktura hierarchiczna</a>
  <ul class="collapse">
<li><a href="#modele-z-ograniczeniami" id="toc-modele-z-ograniczeniami" class="nav-link" data-scroll-target="#modele-z-ograniczeniami">Modele z ograniczeniami</a></li>
  <li><a href="#zasada-hierarchiczno%C5%9Bci-modeli-log-liniowych" id="toc-zasada-hierarchiczności-modeli-log-liniowych" class="nav-link" data-scroll-target="#zasada-hierarchiczno%C5%9Bci-modeli-log-liniowych">Zasada hierarchiczności modeli log-liniowych</a></li>
  <li><a href="#ilustracja-hierarchiczno%C5%9Bci" id="toc-ilustracja-hierarchiczności" class="nav-link" data-scroll-target="#ilustracja-hierarchiczno%C5%9Bci">Ilustracja hierarchiczności</a></li>
  <li><a href="#znaczenie-hierarchiczno%C5%9Bci" id="toc-znaczenie-hierarchiczności" class="nav-link" data-scroll-target="#znaczenie-hierarchiczno%C5%9Bci">Znaczenie hierarchiczności</a></li>
  </ul>
</li>
  <li><a href="#estymacja-parametr%C3%B3w" id="toc-estymacja-parametrów" class="nav-link" data-scroll-target="#estymacja-parametr%C3%B3w">Estymacja parametrów</a></li>
  <li><a href="#ocena-dopasowania" id="toc-ocena-dopasowania" class="nav-link" data-scroll-target="#ocena-dopasowania">Ocena dopasowania</a></li>
  <li><a href="#interpretacja-parametr%C3%B3w" id="toc-interpretacja-parametrów" class="nav-link" data-scroll-target="#interpretacja-parametr%C3%B3w">Interpretacja parametrów</a></li>
  <li><a href="#zera-strukturalne-i-pr%C3%B3bkowe" id="toc-zera-strukturalne-i-próbkowe" class="nav-link" data-scroll-target="#zera-strukturalne-i-pr%C3%B3bkowe">Zera strukturalne i próbkowe</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/DariuszMajerek/WAD_new/issues/new" class="toc-action"><i class="bi bi-github"></i>Zgłoś problem</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span class="chapter-title">Modele log-liniowe</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="rys-historyczny" class="level2"><h2 class="anchored" data-anchor-id="rys-historyczny">Rys historyczny</h2>
<p>Modele log-liniowe wykształciły się w statystyce wielowymiarowej jako narzędzie analizy zależności pomiędzy zmiennymi jakościowymi reprezentowanymi w tabelach kontyngencji. Ich rozwój przypadł na lata 60. i 70. XX wieku, kiedy to poszukiwano metod analogicznych do regresji, zdolnych do opisu wielowymiarowych zależności między kategoriami zmiennych nominalnych. Szczególną rolę odegrały prace Goodmana <span class="citation" data-cites="goodmanSimultaneousConfidenceIntervals1964 goodmanAssociationModelsBivariate1981 goodmanAnalysisCrossClassifiedData1968 goodmanMultivariateAnalysisQualitative1970 goodmanMeasuresAssociationCross1954 goodmanAnalysisMultidimensionalContingency1971">(<a href="references.html#ref-goodmanSimultaneousConfidenceIntervals1964" role="doc-biblioref">Goodman 1964</a>, <a href="references.html#ref-goodmanAssociationModelsBivariate1981" role="doc-biblioref">1981</a>, <a href="references.html#ref-goodmanAnalysisCrossClassifiedData1968" role="doc-biblioref">1968</a>, <a href="references.html#ref-goodmanMultivariateAnalysisQualitative1970" role="doc-biblioref">1970</a>, <a href="references.html#ref-goodmanAnalysisMultidimensionalContingency1971" role="doc-biblioref">1971</a>; <a href="references.html#ref-goodmanMeasuresAssociationCross1954" role="doc-biblioref">Goodman i Kruskal 1954</a>)</span>, które wprowadziły systematyczną parametryzację modeli log-liniowych oraz umożliwiły stosowanie podejścia opartego na maksymalnym prawdopodobieństwie i testowaniu hierarchicznych efektów. W kolejnych dekadach log-liniowe podejścia stały się standardowym narzędziem analizy wielowymiarowych danych kategoryzowanych, a ich teoria ugruntowała się w literaturze statystycznej poświęconej analizie tabel wielodzielczych.</p>
</section><section id="cel" class="level2"><h2 class="anchored" data-anchor-id="cel">Cel</h2>
<p>Główny cel stosowania modeli log-liniowych polegać na opisaniu i wyjaśnieniu struktury zależności pomiędzy więcej niż dwoma zmiennymi jakościowymi. Reprezentacja danych w postaci tabel wielodzielczych prowadzi do konieczności identyfikacji tych komponentów, które odzwierciedlają zależności parowe, trójwymiarowe czy bardziej złożone interakcje między kategoriami. Modele log-liniowe pozwalają odwzorować rozkład częstości poprzez dekompozycję logarytmu oczekiwanych liczności w funkcje efektów głównych i interakcji, dzięki czemu możliwe staje się testowanie hipotez o niezależności lub o strukturze oddziaływań. Stosuje się je zarówno do klasycznych tabel kontyngencji, jak i do danych pochodzących z ankiet, eksperymentów lub badań obserwacyjnych, w których istotna jest struktura współwystępowania kategorii.</p>
</section><section id="definicja-modelu" class="level2"><h2 class="anchored" data-anchor-id="definicja-modelu">Definicja modelu</h2>
<p>Matematyczna definicja modelu log-liniowego opiera się na założeniu, że logarytm wartości oczekiwanej dla każdej komórki tabeli kontyngencji można wyrazić jako suma parametrów związanych z poziomami poszczególnych zmiennych oraz ich współdziałaniem. Dla przykładowej tabeli trójwymiarowej z kategoriami <span class="math inline">\(i\)</span>, <span class="math inline">\(j\)</span> i <span class="math inline">\(k\)</span> model definiujemy w postaci</p>
<p><span class="math display">\[
\log \hat{n}_{ijk} = \lambda + \lambda^X_i + \lambda^Y_j + \lambda^Z_k + \lambda^{XY}_{ij} + \lambda^{XZ}_{ik} + \lambda^{YZ}_{jk} + \lambda^{XYZ}_{ijk},
\]</span> gdzie <span class="math inline">\(\hat{n}_{ijk}\)</span> oznacza wartość oczekiwaną częstości w danej komórce, a poszczególne parametry <span class="math inline">\(\lambda\)</span> odpowiadają efektom głównym i interakcjom efektów W modelach hierarchicznych brak określonego składnika interakcji traktujemy jako hipotezę o niezależności, np. wyeliminowanie <span class="math inline">\(\lambda^{XY}_{ij}\)</span> oznacza neutralność w relacji <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>. Dla jednoznacznej definicji modelu narzuca się warunki sumowalności, takie jak sumowanie współczynników do zera w ramach każdej zmiennej.</p>
</section><section id="struktura-hierarchiczna" class="level2"><h2 class="anchored" data-anchor-id="struktura-hierarchiczna">Struktura hierarchiczna</h2>
<p>W analizie wielowymiarowych tabel kontyngencji model log-liniowy opisuje logarytm wartości oczekiwanych liczebności w komórkach tabeli poprzez sumę efektów głównych i interakcji. Dla trzech zmiennych jakościowych <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span> i <span class="math inline">\(Z\)</span> o kategoriach indeksowanych odpowiednio przez <span class="math inline">\(i\)</span>, <span class="math inline">\(j\)</span> i <span class="math inline">\(k\)</span>, ogólna postać modelu pełnego przyjmuje formę <span class="math display">\[
\log \hat{n}_{ijk} = \lambda + \lambda_i^X + \lambda_j^Y + \lambda_k^Z + \lambda^{XY}_{ij} + \lambda^{XZ}_{ik} + \lambda^{YZ}_{jk} + \lambda^{XYZ}_{ijk}.
\]</span> Składniki te interpretujemy jako:</p>
<ul>
<li>efekt ogólny <span class="math inline">\(\lambda\)</span>,</li>
<li>efekty główne zmiennych <span class="math inline">\(X, Y, Z\)</span>,</li>
<li>interakcje dwuwymiarowe <span class="math inline">\((XY), (XZ), (YZ)\)</span>,</li>
<li>interakcja trójwymiarowa <span class="math inline">\((XYZ)\)</span>.</li>
</ul>
<p>Model pełny zawiera wszystkie możliwe efekty i interakcje.</p>
<section id="modele-z-ograniczeniami" class="level3"><h3 class="anchored" data-anchor-id="modele-z-ograniczeniami">Modele z ograniczeniami</h3>
<p>Usuwanie wybranych interakcji prowadzi do modeli uproszczonych. Przykładowo model bez interakcji trzeciego rzędu ma postać <span class="math display">\[
\log \hat{n}_{ijk} = \lambda + \lambda_i^X + \lambda_j^Y + \lambda_k^Z + \lambda^{XY}_{ij} + \lambda^{XZ}_{ik} + \lambda^{YZ}_{jk}.
\]</span> Model, który zakłada tylko pojedynczą interakcję dwuwymiarową, może mieć postać <span class="math display">\[
\log \hat{n}_{ijk} =\lambda + \lambda_i^X + \lambda_j^Y + \lambda_k^Z + \lambda^{XY}_{ij}.
\]</span> Inne modele eliminują kolejne interakcje lub zachowują tylko część z nich. Każdy taki model musi jednak spełniać zasadę hierarchiczności.</p>
</section><section id="zasada-hierarchiczności-modeli-log-liniowych" class="level3"><h3 class="anchored" data-anchor-id="zasada-hierarchiczności-modeli-log-liniowych">Zasada hierarchiczności modeli log-liniowych</h3>
<p>Model log-liniowy jest hierarchiczny wtedy i tylko wtedy, gdy <strong>obecność jakiejkolwiek interakcji wyższego rzędu wymusza obecność wszystkich jej podinterakcji niższego rzędu</strong>. Formalnie, jeżeli model zawiera interakcję określoną przez zbiór zmiennych <span class="math display">\[
{A_1, A_2, \dots, A_r},
\]</span> to musi on zawierać także wszystkie interakcje zdefiniowane na każdym podzbiorze <span class="math display">\[
{A_{i_1}, A_{i_2}, \dots, A_{i_s}}\subset {A_1, \dots, A_r},
\]</span> a więc również wszystkie efekty główne tworzących tę interakcję zmiennych.</p>
</section><section id="ilustracja-hierarchiczności" class="level3"><h3 class="anchored" data-anchor-id="ilustracja-hierarchiczności">Ilustracja hierarchiczności</h3>
<p>Jeżeli w modelu pozostawia się interakcję trzeciego rzędu <span class="math inline">\(\lambda^{XYZ}_{ijk},\)</span> to model musi dodatkowo zawierać:</p>
<ul>
<li>interakcje dwuwymiarowe <span class="math display">\[
\lambda^{XY}_{ij}, \ \lambda^{XZ}_{ik}, \ \lambda^{YZ}_{jk},
\]</span>
</li>
<li>oraz efekty główne: <span class="math display">\[
\lambda_i^X,\ \lambda_j^Y,\ \lambda_k^Z,
\]</span>
</li>
<li>a także efekt ogólny <span class="math inline">\(\lambda\)</span>.</li>
</ul>
<p>Analogicznie, jeżeli model zawiera interakcję dwuwymiarową, np. <span class="math inline">\(\lambda^{XY}_{ij}\)</span>, to musi jednocześnie zawierać: <span class="math display">\[
\lambda_i^X,\qquad \lambda_j^Y,\qquad \lambda.
\]</span> Model, w którym te warunki nie są spełnione, nie jest modelem hierarchicznym.</p>
</section><section id="znaczenie-hierarchiczności" class="level3"><h3 class="anchored" data-anchor-id="znaczenie-hierarchiczności">Znaczenie hierarchiczności</h3>
<p>Hierarchiczność zapewnia:</p>
<ul>
<li>spójną, poprawną interpretację parametrów,</li>
<li>istnienie estymatorów maksymalnego prawdopodobieństwa,</li>
<li>prawidłowe działanie algorytmu iteracyjnego dopasowania proporcjonalnego (IPF),</li>
<li>logiczną strukturę zależności pomiędzy zmiennymi.</li>
</ul>
<p>W efekcie stanowi podstawową zasadę konstrukcji modeli log-liniowych i gwarantuje ich poprawność statystyczną.</p>
</section></section><section id="estymacja-parametrów" class="level2"><h2 class="anchored" data-anchor-id="estymacja-parametrów">Estymacja parametrów</h2>
<p>W modelach log-liniowych parametry estymuje się w oparciu o zasadę maksymalizacji funkcji wiarygodności. Przyjmuje się, że liczności tabeli kontyngencji mają rozkład Poissona z parametrami <span class="math inline">\(\hat{n}_{ijk}\)</span>, które odpowiadają wartościom oczekiwanym wynikającym z przyjętego modelu log-liniowego. Konstrukcja funkcji wiarygodności opiera się na fakcie, że komórki są traktowane jako niezależne, co prowadzi do iloczynu gęstości Poissona. Logarytm takiej funkcji dla tabeli trójwymiarowej przyjmuje postać <span class="math display">\[
\ell(\lambda) = \sum_{ijk}
\left[
n_{ijk} \log(\hat{n}_{ijk}) - \hat{n}_{ijk} - \log(n_{ijk}!)
\right],
\]</span></p>
<p>gdzie <span class="math inline">\(n_{ijk}\)</span> oznacza liczbę obserwacji w komórce <span class="math inline">\(ijk\)</span>, a <span class="math inline">\(\hat{n}_{ijk}\)</span> wartość oczekiwaną określoną przez model. Po odrzuceniu stałej <span class="math inline">\(\log(n_{ijk}!)\)</span> zadanie estymacji sprowadza się do maksymalizacji <span class="math display">\[
\ell(\lambda) =\sum_{ijk}
\left[
n_{ijk},\log(\hat{n}_{ijk}) - \hat{n}_{ijk}
\right],
\]</span> przy czym <span class="math inline">\(\hat{n}_{ijk}\)</span> wyrażane są w funkcji parametrów <span class="math inline">\(\lambda\)</span>, ponieważ model określa <span class="math display">\[
\log(\hat{n}_{ijk}) = \lambda + \lambda_{i}^A + \lambda_{j}^B + \lambda_{k}^C + \lambda_{ij}^{AB} + \dots
\]</span> Wobec nieliniowości tej struktury warunki pierwszego rzędu nie mają zamkniętego rozwiązania algebraicznego, co prowadzi do konieczności wykorzystania metod iteracyjnych. W zastosowaniach modeli log-liniowych wykorzystuje się dwie klasy procedur. Pierwsza opiera się na iteracyjnych metodach gradientowych, takich jak Newton–Raphson, w których aktualizuje się wartości parametrów poprzez dodawanie poprawek proporcjonalnych do pochodnej pierwszej i odwrotności hessianu. Druga klasa, szczególnie rozpowszechniona w analizie tabel wielodzielczych, wykorzystuje algorytm <em>iterative proportional fitting</em> (IPF).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Adnotacja
</div>
</div>
<div class="callout-body-container callout-body">
<p>Algorytm <em>iterative proportional fitting</em> (IPF) stosuje się do wyznaczania wartości oczekiwanych <span class="math inline">\(n_{i_1 i_2 \dots i_p}\)</span> w modelach log-liniowych tak, aby były one zgodne z zadanymi rozkładami brzegowymi wynikającymi z przyjętej struktury modelu hierarchicznego. Sednem tej procedury jest kolejne skalowanie fragmentów tabeli oczekiwanej w taki sposób, aby dopasować ich marginesy do marginesów danych empirycznych. Iteracja po iteracji kolejne rozkłady brzegowe zaczynają odpowiadać odpowiednim sumom brzegowym obserwacji, co w rezultacie prowadzi do wartości oczekiwanych maksymalizujących funkcję wiarygodności.</p>
<p>Przykładowo dla modelu bez interakcji trzeciego rzędu <span class="math display">\[
\log(\hat{n}_{ijk}) = \lambda + \lambda_i^X + \lambda_j^Y + \lambda_k^Z + \lambda_{ij}^{XY} + \lambda_{ik}^{XZ} + \lambda_{jk}^{YZ},
\]</span> czyli model, w którym wyklucza się obecność interakcji trójwymiarowej <span class="math inline">\((XYZ)\)</span>. W takim modelu estymatory wartości oczekiwanych <span class="math inline">\(\hat{n}_{ijk}\)</span> muszą spełniać trzy zestawy warunków brzegowych: <span class="math display">\[
\hat{n}_{ij\cdot}=n_{ij\cdot},\qquad
\hat{n}_{i\cdot k}=n_{i\cdot k},\qquad
\hat{n}_{\cdot jk}=n_{\cdot jk}.
\]</span> Warunki te nie mogą zostać spełnione przez bezpośrednie podstawienie parametrów do równania log-liniowego, dlatego stosuje się procedurę iteracyjną IPF.</p>
<section id="krok-0.-wybór-wartości-początkowych" class="level3"><h3 class="anchored" data-anchor-id="krok-0.-wybór-wartości-początkowych">Krok 0. Wybór wartości początkowych</h3>
<p>Procedurę rozpoczyna się od zadania początkowych wartości liczebności oczekiwanych: <span class="math display">\[
\hat{n}_{ijk}^{(0)} = 1 \qquad \text{dla wszystkich } i,j,k.
\]</span></p>
</section><section id="krok-1.-dopasowanie-marginesów-hatn_ijcdot" class="level3"><h3 class="anchored" data-anchor-id="krok-1.-dopasowanie-marginesów-hatn_ijcdot">Krok 1. Dopasowanie marginesów <span class="math inline">\(\hat{n}_{ij\cdot}\)</span>
</h3>
<p>Aby wymusić spełnienie zależności <span class="math display">\[
\hat{n}_{ij\cdot} = n_{ij\cdot},
\]</span> stosuje się skalowanie proporcjonalne w każdej warstwie <span class="math inline">\(k\)</span> <span class="math display">\[
\hat{n}_{ijk}^{(1)} = \frac{\hat{n}_{ijk}^{(0)}\cdot n_{ij\cdot}}{\hat{n}_{ij\cdot}^{(0)}}.
\]</span></p>
<p>Wartości <span class="math inline">\(\hat{n}_{ij\cdot}^{(0)}\)</span> oznaczają marginesy wyliczone z tabeli <span class="math inline">\(\hat{n}^{(0)}\)</span>. Po zastosowaniu tego skalowania nowe liczebności <span class="math inline">\(\hat{n}^{(1)}\)</span> mają prawidłowe marginesy <span class="math inline">\((XY)\)</span>.</p>
</section><section id="krok-2.-dopasowanie-marginesów-hatn_icdot-k" class="level3"><h3 class="anchored" data-anchor-id="krok-2.-dopasowanie-marginesów-hatn_icdot-k">Krok 2. Dopasowanie marginesów <span class="math inline">\(\hat{n}_{i\cdot k}\)</span>
</h3>
<p>Teraz narzuca się spełnienie warunku <span class="math display">\[
\hat{n}_{i\cdot k} = n_{i\cdot k}.
\]</span></p>
<p>Wykorzystując liczebności <span class="math inline">\(\hat{n}_{ijk}^{(1)}\)</span> z poprzedniego kroku, dokonuje się skalowania <span class="math display">\[
\hat{n}_{ijk}^{(2)} = \frac{\hat{n}_{ijk}^{(1)}\cdot n_{i\cdot k}}{\hat{n}_{i\cdot k}^{(1)}}.
\]</span> Po tym kroku wartości oczekiwane <span class="math inline">\(\hat{n}^{(2)}\)</span> spełniają ograniczenia dotyczące marginesów <span class="math inline">\((XZ)\)</span>.</p>
</section><section id="krok-3.-dopasowanie-marginesów-hatn_cdot-jk" class="level3"><h3 class="anchored" data-anchor-id="krok-3.-dopasowanie-marginesów-hatn_cdot-jk">Krok 3. Dopasowanie marginesów <span class="math inline">\(\hat{n}_{\cdot jk}\)</span>
</h3>
<p>Aby spełnić trzecie ograniczenie <span class="math display">\[
\hat{n}_{\cdot jk} = n_{\cdot jk},
\]</span> stosuje się kolejne skalowanie <span class="math display">\[
\hat{n}_{ijk}^{(3)} = \frac{\hat{n}_{ijk}^{(2)}\cdot n_{\cdot jk}}{\hat{n}_{\cdot jk}^{(2)}}.
\]</span> Po tym kroku liczebności <span class="math inline">\(\hat{n}^{(3)}\)</span> mają prawidłowe marginesy <span class="math inline">\((YZ)\)</span>.</p>
</section><section id="krok-4.-kolejne-cykle" class="level3"><h3 class="anchored" data-anchor-id="krok-4.-kolejne-cykle">Krok 4. Kolejne cykle</h3>
<p>Aby zakończyć pierwszy pełny cykl dopasowań, wraca się do kroku 1, podstawiając <span class="math inline">\(\hat{n}_{ijk}^{(3)}\)</span> jako wartości wejściowe <span class="math display">\[
\hat{n}_{ijk}^{(3)} \longrightarrow \hat{n}_{ijk}^{(0)} \text{ w kolejnym cyklu}.
\]</span></p>
<p>Procedura powtarza się w kolejności:</p>
<ol type="1">
<li>dopasowanie <span class="math inline">\((XY)\)</span>,</li>
<li>dopasowanie <span class="math inline">\((XZ)\)</span>,</li>
<li>dopasowanie <span class="math inline">\((YZ)\)</span>,</li>
</ol>
<p>aż do osiągnięcia zbieżności.</p>
</section><section id="zakończenie-algorytmu" class="level3"><h3 class="anchored" data-anchor-id="zakończenie-algorytmu">Zakończenie algorytmu</h3>
<p>Iteracje kontynuuje się do momentu, w którym różnice między kolejnymi tabelami <span class="math inline">\(\hat{n}^{(t)}\)</span> i <span class="math inline">\(\hat{n}^{(t+1)}\)</span> nie przekraczają ustalonej tolerancji, np.: <span class="math display">\[
|\hat{n}_{ijk}^{(t+1)} - \hat{n}_{ijk}^{(t)}| &lt; 0.01
\]</span></p>
<p>dla wszystkich <span class="math inline">\(i,j,k\)</span>.</p>
</section><section id="uwagi-końcowe" class="level3"><h3 class="anchored" data-anchor-id="uwagi-końcowe">Uwagi końcowe</h3>
<ul>
<li>Jeśli brzegowe liczebności oczekiwane mogą być bezpośrednio wyliczone z danych empirycznych (np. w modelach pełnych), algorytm IPF nie jest konieczny.</li>
<li>W modelach hierarchicznych brakujących interakcji (np. brak <span class="math inline">\((XYZ)\)</span>) IPF jest jedyną wygodną metodą prowadzącą do estymacji maksymalnego prawdopodobieństwa.</li>
<li>Dowodzi się, że IPF zawsze zbiega do unikalnego rozwiązania MLE, o ile marginesy nie zawierają niemożliwych konfiguracji (Haberman, 1974).</li>
</ul></section>
</div>
</div>
</section><section id="ocena-dopasowania" class="level2"><h2 class="anchored" data-anchor-id="ocena-dopasowania">Ocena dopasowania</h2>
<p>Ocena poprawności modelu możliwa jest poprzez porównanie wartości oczekiwanych i zaobserwowanych liczności. Najczęściej stosuje się test statystyki ilorazu wiarygodności, <span class="math display">\[
G^2 = 2 \sum_{ijk} n_{ijk} \log\left(\frac{n_{ijk}}{\hat{n}_{ijk}}\right),
\]</span></p>
<p>lub test chi-kwadrat Pearsona (rzadziej używany), <span class="math display">\[
\chi^2 = \sum_{ijk} \frac{(n_{ijk} - \hat{n}_{ijk})^2}{\hat{n}_{ijk}}.
\]</span> Obie statystyki pozwalają ocenić zgodność modelu z danymi, przy czym mniejsze wartości <span class="math inline">\(G^2\)</span> i <span class="math inline">\(\chi^2\)</span> wskazują na lepsze dopasowanie. Kryteria informacyjne, takie jak AIC i BIC, umożliwiają porównanie modeli o różnej strukturze interakcji, natomiast analiza reszt pozwala wychwycić lokalne odchylenia. Sprawdza się także warunki hierarchiczności oraz stabilność parametrów względem zmian tabeli.</p>
</section><section id="interpretacja-parametrów" class="level2"><h2 class="anchored" data-anchor-id="interpretacja-parametrów">Interpretacja parametrów</h2>
<p>Interpretacja modelu log-liniowego odwołuje się do koncepcji proporcji i współczynników intensywności zależności. Parametry w skali logarytmicznej odpowiadają ilorazom intensywności współwystępowania kategorii. Dla efektów głównych porównuje się poziomy zmiennych w odniesieniu do kategorii bazowych, natomiast dla interakcji parametry wskazują na istnienie lub brak oddziaływania pomiędzy zmiennymi. Na przykład dodatnia wartość parametru interakcji <span class="math inline">\(\lambda^{XY}_{ij}\)</span> oznacza, że kombinacja kategorii <span class="math inline">\(i\)</span> i <span class="math inline">\(j\)</span> występuje częściej niż wynikałoby to z ich niezależności, natomiast wartości ujemne sugerują niedoreprezentowanie tej pary. Interpretacja w kontekście ilorazów szans umożliwia przekształcenie parametrów do skali relatywnej, użytecznej w analizach porównawczych.</p>
<p>Model log-liniowy stanowi zatem metodę pozwalającą odwzorować strukturę zależności w danych jakościowych poprzez analizę efektów głównych i interakcji zmiennych. Łączy zasady modeli Poissona, hierarchicznej struktury tabeli oraz testowania hipotez o niezależności, stanowiąc uniwersalne narzędzie analityczne w badaniach wielowymiarowych.</p>
</section><section id="zera-strukturalne-i-próbkowe" class="level2"><h2 class="anchored" data-anchor-id="zera-strukturalne-i-próbkowe">Zera strukturalne i próbkowe</h2>
<p>W analizie tabel wielodzielczych <em>zera strukturalne</em> i <em>zera próbkowe</em> odnoszą się do komórek o liczebności równej zero, lecz różnią się znaczeniem i konsekwencjami dla modelowania. W obu przypadkach komórka ma wartość 0, ale interpretacja tego zera jest zupełnie inna, co wpływa na możliwość stosowania modeli log-liniowych oraz na ich dopasowanie.</p>
<p>Zerem <strong>strukturalnym</strong> nazywa się taką komórkę tabeli, w której liczebność musi wynosić zero ze względu na logikę lub reguły konstrukcji zjawiska. Oznacza to, że taka kategoria w ogóle nie może wystąpić w populacji i obserwacja jej byłaby sprzeczna z definicją zmiennych. Przykładowo, w tabeli krzyżującej płeć biologiczną (mężczyzna, kobieta) z kategorią „ciąża” (tak, nie), komórka „mężczyzna, ciąża = tak” jest zerem strukturalnym, bo z definicji nie może być tam żadnej obserwacji. Podobnie w tabeli krzyżującej wiek w kategoriach (0–17, 18+) z „posiadanie prawa wyborczego” (tak, nie), komórka „wiek 0–17, prawo wyborcze = tak” jest zerem strukturalnym.</p>
<p>Zera <strong>próbkowe</strong> (ang. <em>sampling zeros</em>) oznaczają tych przypadki, w których liczebność komórki wynosi zero tylko dlatego, że w danym losowaniu lub próbie nie zaobserwowano żadnej jednostki pasującej do danej kombinacji kategorii, choć w populacji jest ona możliwa. Przykładem może być komórka tabeli wiążącej wykształcenie i rodzaj wykonywanej pracy, gdzie w próbie nie odnotowano osoby z wykształceniem podstawowym zatrudnionej jako programista, mimo że taka kombinacja jest realnie możliwa. Innym przykładem jest tabela preferencji zakupowych, w której żadna osoba w próbie nie wybrała połączenia „płeć męska” i „zakup kosmetyków naturalnych”, mimo że taka decyzja zakupowa może wystąpić w populacji.</p>
<p>Różnica między tymi dwoma typami zer jest istotna, ponieważ zera strukturalne wymagają wyłączenia odpowiednich komórek z analizy lub użycia modeli uwzględniających ograniczenia, natomiast zera próbkowe można traktować jako wynik losowej fluktuacji w próbie i uwzględniać normalnie w dopasowaniu modeli log-liniowych.</p>
<p>Co robimy w modelu log-liniowym:</p>
<ul>
<li>w przypadku niekompletnych tablic z zerami strukturalnymi liczbę stopni swobody rozkładu <span class="math inline">\(\chi^2\)</span> statystyki <span class="math inline">\(\chi^2\)</span> (lub <span class="math inline">\(G^2\)</span>) określa formuła <span class="math inline">\(df= n_1−n_2−n_3,\)</span> gdzie <span class="math inline">\(n_1\)</span> to liczba komórek w tabeli, <span class="math inline">\(n_2\)</span> to liczba parametrów w modelu wymagających estymacji, a <span class="math inline">\(n_3\)</span> to liczba zer <em>a priori</em>.</li>
<li>rozwiązaniem problemu występowania zer próbkowych jest zwiększenie liczebności próbki lub ewentualnie, jeśli jest to niemożliwe, zwiększenie wszystkich liczebności oczekiwanych przez dodanie małej stałej, zwykle <span class="math inline">\(\Delta = 0.5\)</span>, do każdej komórki tabeli (tzw. korekta Haldane’).</li>
</ul>
<div id="exm-1" class="theorem example">
<p><span class="theorem-title"><strong>Przykład 8.1</strong></span> &nbsp;</p>
<ol type="1">
<li>Dane i pytanie badawcze</li>
</ol>
<p>Wbudowany zbiór <code>HairEyeColor</code> opisuje liczbę osób (uczestników badania), skategoryzowanych według:</p>
<ul>
<li>
<code>Hair</code>: kolor włosów (Black, Brown, Red, Blond),</li>
<li>
<code>Eye</code>: kolor oczu (Brown, Blue, Hazel, Green),</li>
<li>
<code>Sex</code>: płeć (Male, Female).</li>
</ul>
<p>Pytania badawcze:</p>
<ul>
<li>czy kolor włosów i oczu są od siebie niezależne?</li>
<li>czy zależność włosy–oczy jest taka sama dla kobiet i mężczyzn?</li>
<li>czy płeć wnosi jakąś istotną interakcję?</li>
</ul>
<ol start="2" type="1">
<li>Wczytanie danych i podstawowa eksploracja</li>
</ol>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># wczytanie danych</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">HairEyeColor</span><span class="op">)</span></span>
<span><span class="va">HairEyeColor</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>, , Sex = Male

       Eye
Hair    Brown Blue Hazel Green
  Black    32   11    10     3
  Brown    53   50    25    15
  Red      10   10     7     7
  Blond     3   30     5     8

, , Sex = Female

       Eye
Hair    Brown Blue Hazel Green
  Black    36    9     5     2
  Brown    66   34    29    14
  Red      16    7     7     7
  Blond     4   64     5     8</code></pre>
</div>
</div>
<p>Zamieniamy go na ramkę danych:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">HairEyeColor</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">hec</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>   Hair   Eye  Sex Freq
1 Black Brown Male   32
2 Brown Brown Male   53
3   Red Brown Male   10
4 Blond Brown Male    3
5 Black  Blue Male   11
6 Brown  Blue Male   50</code></pre>
</div>
</div>
<p>Można też sprawdzić proste tablice brzegowe:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># tablica 2D włosy × oczy (bez rozróżnienia płci)</span></span>
<span><span class="op">(</span><span class="va">HairEye</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/marginSums.html">margin.table</a></span><span class="op">(</span><span class="va">HairEyeColor</span>, margin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Eye
Hair    Brown Blue Hazel Green
  Black    68   20    15     5
  Brown   119   84    54    29
  Red      26   17    14    14
  Blond     7   94    10    16</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># tablica 2D włosy × płeć</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/marginSums.html">margin.table</a></span><span class="op">(</span><span class="va">HairEyeColor</span>, margin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Sex
Hair    Male Female
  Black   56     52
  Brown  143    143
  Red     34     37
  Blond   46     81</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># tablica 2D oczy × płeć</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/marginSums.html">margin.table</a></span><span class="op">(</span><span class="va">HairEyeColor</span>, margin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Sex
Eye     Male Female
  Brown   98    122
  Blue   101    114
  Hazel   47     46
  Green   33     31</code></pre>
</div>
</div>
<p>Już na tym etapie można zauważyć, że np. brązowe włosy i brązowe oczy są najczęstsze.</p>
<ol start="3" type="1">
<li>Idea modelu <em>log-liniowego</em>
</li>
</ol>
<p>Zmienna <code>Freq</code> (liczebność komórki tabeli) traktowana jest jako zmienna o rozkładzie Poissona z wartością oczekiwaną <span class="math inline">\(n_{ijk}\)</span>. Model <em>log-liniowy</em> zakłada, że <span class="math display">\[
\log \hat{n}_{ijk} = \lambda + \lambda_i^{Hair} + \lambda_j^{Eye} + \lambda_k^{Sex} + \lambda_{ij}^{Hair:Eye} + \lambda_{ik}^{Hair:Sex} +  \lambda_{jk}^{Eye:Sex} + \lambda_{ijk}^{Hair:Eye:Sex}.
\]</span> To jest model pełny (nasycony, ang. <em>saturated model</em>), który zawsze perfekcyjnie odtwarza liczebności obserwowane. Chcąc znaleźć model optymalny, eliminujemy z modelu nasyconego poszczególne efekty interakcji, zaczynając od interakcji najwyższego rzędu.</p>
<ol start="4" type="1">
<li>Model pełny (nasycony)</li>
</ol>
<p>Do estymacji użyjemy funkcji <code>loglm</code> z pakietu <code>MASS</code>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span><span class="va">m_full</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="va">Freq</span> <span class="op">~</span> <span class="va">Hair</span> <span class="op">*</span> <span class="va">Eye</span> <span class="op">*</span> <span class="va">Sex</span>, data <span class="op">=</span> <span class="va">hec</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_full</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Formula:
Freq ~ Hair * Eye * Sex
attr(,"variables")
list(Freq, Hair, Eye, Sex)
attr(,"factors")
     Hair Eye Sex Hair:Eye Hair:Sex Eye:Sex Hair:Eye:Sex
Freq    0   0   0        0        0       0            0
Hair    1   0   0        1        1       0            1
Eye     0   1   0        1        0       1            1
Sex     0   0   1        0        1       1            1
attr(,"term.labels")
[1] "Hair"         "Eye"          "Sex"          "Hair:Eye"     "Hair:Sex"    
[6] "Eye:Sex"      "Hair:Eye:Sex"
attr(,"order")
[1] 1 1 1 2 2 2 3
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
&lt;environment: R_GlobalEnv&gt;
attr(,"predvars")
list(Freq, Hair, Eye, Sex)
attr(,"dataClasses")
     Freq      Hair       Eye       Sex 
"numeric"  "factor"  "factor"  "factor" 

Statistics:
                 X^2 df P(&gt; X^2)
Likelihood Ratio   0  0        1
Pearson            0  0        1</code></pre>
</div>
</div>
<p>W formule symbol <code>*</code> oznacza wszystkie efekty główne i interakcje do danego rzędu. <code>Hair * Eye * Sex</code> odpowiada zapisowi <code>Hair + Eye + Sex + Hair:Eye + Hair:Sex + Eye:Sex + Hair:Eye:Sex</code></p>
<p>Jak widać na podstawie statystyk dopasowania <span class="math inline">\(G^2\)</span> i <span class="math inline">\(\chi^2\)</span> model idealnie dopasowuje się do danych (<code>deviance = 0, p-value = 1</code>).</p>
<ol start="5" type="1">
<li>Model niezależności wszystkich trzech zmiennych</li>
</ol>
<p>Teraz bardzo restrykcyjny model:</p>
<ul>
<li>zakłada się pełną niezależność <code>Hair</code>, <code>Eye</code> i <code>Sex</code>,</li>
<li>brak jakichkolwiek interakcji.</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_indep</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="va">Freq</span> <span class="op">~</span> <span class="va">Hair</span> <span class="op">+</span> <span class="va">Eye</span> <span class="op">+</span> <span class="va">Sex</span>, data <span class="op">=</span> <span class="va">hec</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_indep</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Formula:
Freq ~ Hair + Eye + Sex
attr(,"variables")
list(Freq, Hair, Eye, Sex)
attr(,"factors")
     Hair Eye Sex
Freq    0   0   0
Hair    1   0   0
Eye     0   1   0
Sex     0   0   1
attr(,"term.labels")
[1] "Hair" "Eye"  "Sex" 
attr(,"order")
[1] 1 1 1
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
&lt;environment: R_GlobalEnv&gt;
attr(,"predvars")
list(Freq, Hair, Eye, Sex)
attr(,"dataClasses")
     Freq      Hair       Eye       Sex 
"numeric"  "factor"  "factor"  "factor" 

Statistics:
                      X^2 df P(&gt; X^2)
Likelihood Ratio 166.3001 24        0
Pearson          164.9247 24        0</code></pre>
</div>
</div>
<p>Na podstawie wyników można stwierdzić, że model złożony jedynie z efektów brzegowych jest niewystarczający do opisu związków między cechami.</p>
<ol start="6" type="1">
<li>Model testujący czy kolor włosów i oczu są od siebie niezależne</li>
</ol>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_HE_indep</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="va">Freq</span> <span class="op">~</span> <span class="va">Hair</span> <span class="op">+</span> <span class="va">Eye</span>, data <span class="op">=</span> <span class="va">hec</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_HE_indep</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Formula:
Freq ~ Hair + Eye
attr(,"variables")
list(Freq, Hair, Eye)
attr(,"factors")
     Hair Eye
Freq    0   0
Hair    1   0
Eye     0   1
attr(,"term.labels")
[1] "Hair" "Eye" 
attr(,"order")
[1] 1 1
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
&lt;environment: R_GlobalEnv&gt;
attr(,"predvars")
list(Freq, Hair, Eye)
attr(,"dataClasses")
     Freq      Hair       Eye 
"numeric"  "factor"  "factor" 

Statistics:
                      X^2 df P(&gt; X^2)
Likelihood Ratio 168.2539 25        0
Pearson          171.5907 25        0</code></pre>
</div>
</div>
<p>Model <code>m_HE_indep</code> reprezentuje <strong>model niezależności</strong> między kolorem włosów (<code>Hair</code>) i kolorem oczu (<code>Eye</code>). Odczytane statystyki pozwalają sprawdzić, czy hipoteza niezależności jest zgodna z danymi.</p>
<ul>
<li>Model zakłada, że <span class="math inline">\(H_0: Hair \perp Eye\)</span> czyli brak interakcji <code>Hair:Eye</code>, co oznacza, że struktura częstości włosów i oczu powinna wynikać wyłącznie z ich rozkładów marginalnych.</li>
<li>Statystyki dopasowania <span class="math inline">\(G^2 = 168.25\)</span>, <span class="math inline">\(p = 0\)</span> oraz <span class="math inline">\(\chi^2 = 171.59\)</span>, <span class="math inline">\(p = 0\)</span> wskazują na bardzo słabe dopasowanie modelu do danych.</li>
<li>Kolor włosów i kolor oczu są <strong>wyraźnie zależne</strong>. W tabeli występują kombinacje kolorów włosów i oczu, które pojawiają się częściej lub rzadziej, niż przewiduje model niezależności.</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_HE_indep</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Re-fitting to get fitted values</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>, , .Within. = 1

       Eye
Hair       Brown     Blue     Hazel     Green
  Black 20.06757 19.61149  8.483108  5.837838
  Brown 53.14189 51.93412 22.464527 15.459459
  Red   13.19257 12.89274  5.576858  3.837838
  Blond 23.59797 23.06166  9.975507  6.864865

, , .Within. = 2

       Eye
Hair       Brown     Blue     Hazel     Green
  Black 20.06757 19.61149  8.483108  5.837838
  Brown 53.14189 51.93412 22.464527 15.459459
  Red   13.19257 12.89274  5.576858  3.837838
  Blond 23.59797 23.06166  9.975507  6.864865</code></pre>
</div>
</div>
<p>Wartości przedstawione jako <code>fitted(m_HE_indep)</code> to liczebności <strong>oczekiwane</strong> w modelu zakładającym <strong>niezależność</strong> koloru włosów i koloru oczu. Otrzymane tablice mają identyczne wartości dla obu poziomów płci, ponieważ model niezależności nie uwzględnia płci – liczy wyłącznie to, jakie liczebności powinny wystąpić przy produkcie marginesów Hair i Eye.</p>
<p>Każda komórka pokazuje zatem, ile osób <em>powinno</em> znaleźć się w danej kombinacji kolorów włosów i oczu, gdyby te cechy były od siebie niezależne. Porównanie tych wartości z liczebnościami obserwowanymi (które silnie od nich odbiegają) ilustruje, że model niezależności nie opisuje danych poprawnie, co potwierdza wcześniejszy test odrzucający hipotezę niezależności Hair–Eye.</p>
<ol start="7" type="1">
<li>Model testujący czy zależność Hair–Eye jest taka sama dla kobiet i mężczyzn</li>
</ol>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_no3way</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="va">Freq</span> <span class="op">~</span> <span class="op">(</span><span class="va">Hair</span> <span class="op">+</span> <span class="va">Eye</span> <span class="op">+</span> <span class="va">Sex</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>, data <span class="op">=</span> <span class="va">hec</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_no3way</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Formula:
Freq ~ (Hair + Eye + Sex)^2
attr(,"variables")
list(Freq, Hair, Eye, Sex)
attr(,"factors")
     Hair Eye Sex Hair:Eye Hair:Sex Eye:Sex
Freq    0   0   0        0        0       0
Hair    1   0   0        1        1       0
Eye     0   1   0        1        0       1
Sex     0   0   1        0        1       1
attr(,"term.labels")
[1] "Hair"     "Eye"      "Sex"      "Hair:Eye" "Hair:Sex" "Eye:Sex" 
attr(,"order")
[1] 1 1 1 2 2 2
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
&lt;environment: R_GlobalEnv&gt;
attr(,"predvars")
list(Freq, Hair, Eye, Sex)
attr(,"dataClasses")
     Freq      Hair       Eye       Sex 
"numeric"  "factor"  "factor"  "factor" 

Statistics:
                      X^2 df  P(&gt; X^2)
Likelihood Ratio 6.761258  9 0.6619600
Pearson          6.868292  9 0.6508299</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Porównanie modeli zagnieżdżonych (test LRT)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m_no3way</span>, <span class="va">m_full</span>, test <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>LR tests for hierarchical log-linear models

Model 1:
 Freq ~ (Hair + Eye + Sex)^2 
Model 2:
 Freq ~ Hair * Eye * Sex 

          Deviance df Delta(Dev) Delta(df) P(&gt; Delta(Dev)
Model 1   6.761258  9                                    
Model 2   0.000000  0   6.761258         9        0.66196
Saturated 0.000000  0   0.000000         0        1.00000</code></pre>
</div>
</div>
<p>Model zawierający wszystkie interakcje drugiego rzędu, ale pozbawiony interakcji trzeciego rzędu, charakteryzuje się bardzo dobrym dopasowaniem do danych. Wysokie wartości p-value zarówno dla statystyki ilorazu wiarygodności, jak i testu Pearsona wskazują, że różnice pomiędzy wartościami obserwowanymi a oczekiwanymi nie są istotne. Oznacza to, że model w tej postaci potrafi odtworzyć strukturę danych i nie ma podstaw do wnioskowania, że brakuje w nim istotnej zależności.</p>
<p>Porównanie tego modelu z modelem nasyconym, który dodatkowo zawiera interakcję trzeciego rzędu, również nie pokazuje istotnych różnic. Wartość <span class="math inline">\(p\)</span> dla różnicy <em>deviance</em> pomiędzy modelami jest wysoka, co wskazuje, że dodanie interakcji trójwymiarowej nie poprawia jakości dopasowania. Oznacza to, że zależności pomiędzy parami zmiennych w pełni wyjaśniają obserwowaną strukturę, a interakcja trzeciego rzędu nie wnosi dodatkowej informacji.</p>
<p>Wynik testów oznacza, że zależność między kolorem włosów a kolorem oczu <strong>jest taka sama dla kobiet i mężczyzn</strong>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_no3way</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Re-fitting to get fitted values</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>, , Sex = Male

       Eye
Hair        Brown      Blue     Hazel     Green
  Black 32.789022 11.743604  8.443926  3.018481
  Brown 52.523050 45.931148 28.195250 16.348213
  Red   10.760485  8.819775  6.916602  7.502671
  Blond  1.927443 34.505472  3.444222  6.130636

, , Sex = Female

       Eye
Hair        Brown      Blue     Hazel     Green
  Black 35.208836  8.258511  6.556304  1.981916
  Brown 66.477232 38.072151 25.804202 12.652225
  Red   15.239924  8.180608  7.083293  6.497414
  Blond  5.074007 59.488731  6.556201  9.868446</code></pre>
</div>
</div>
<p>Wartości <code>fitted(m_no3way)</code> przedstawiają liczebności oczekiwane w modelu, który uwzględnia wszystkie <strong>interakcje drugiego rzędu</strong> (Hair:Eye, Hair:Sex, Eye:Sex), ale pomija interakcję trzeciego rzędu. Oczekiwane liczebności różnią się między kobietami a mężczyznami, ponieważ model dopuszcza wpływ płci na rozkład włosów oraz na rozkład oczu, a także oddzielnie na zależność każdej z tych cech z płcią.</p>
<p>Rozkład liczebności oczekiwanych w każdej płci odzwierciedla różnice marginesów i dwuwymiarowych zależności w podtabelach, ale brak interakcji trzeciego rzędu sprawia, że wzorce zależności między kolorem włosów i kolorem oczu są nakładane symetrycznie w każdej płci. Oznacza to, że model dopuszcza różnice w częstości kategorii włosów i oczu między kobietami a mężczyznami, lecz zakłada, że trójwymiarowy wzorzec współwystępowania tych cech nie zawiera dodatkowej struktury uzależnionej od płci.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">m_no3way</span><span class="op">$</span><span class="va">param</span><span class="op">$</span><span class="va">Eye.Sex</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Sex
Eye          Male    Female
  Brown 0.8564811 1.1675681
  Blue  1.0583498 0.9448672
  Hazel 1.0072147 0.9928370
  Green 1.0952946 0.9129963</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">m_no3way</span><span class="op">$</span><span class="va">param</span><span class="op">$</span><span class="va">Hair.Sex</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Sex
Hair         Male    Female
  Black 1.1820456 0.8459910
  Brown 1.0887655 0.9184714
  Red   1.0292488 0.9715824
  Blond 0.7549376 1.3246128</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">m_no3way</span><span class="op">$</span><span class="va">param</span><span class="op">$</span><span class="va">Hair.Eye</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Eye
Hair        Brown      Blue    Hazel     Green
  Black 2.7189690 0.6650995 1.109218 0.4985309
  Brown 1.3349516 0.7973193 1.135242 0.8275872
  Red   1.0601658 0.5934837 1.079522 1.4722643
  Blond 0.2598701 3.1774030 0.735636 1.6462976</code></pre>
</div>
</div>
<p>Wartości parametrów w postaci wykładniczej (czyli po zastosowaniu funkcji <code>exp</code>) pokazują względne ilorazy częstości dla poszczególnych efektów dwuwymiarowych obecnych w modelu. Dla testowanej hipotezy dotyczącej obecności lub braku istotnej interakcji z płcią wartościowe są wyłącznie parametry dotyczące relacji <code>Eye:Sex</code> oraz <code>Hair:Sex</code>. To one informują, czy rozkład kategorii oczu lub włosów różni się pomiędzy kobietami i mężczyznami po uwzględnieniu pozostałych efektów w modelu. Ilorazy większe od 1 wskazują, że dana kombinacja (np. kategoria oczu u mężczyzn) występuje częściej, niż wynikałoby to z modelu bez tej interakcji, natomiast wartości mniejsze od 1 informują o relatywnym niedoborze obserwacji. Przykładowo, wartość 0.856 oznacza, że liczebność mężczyzn o brązowych oczach jest o około 14 procent niższa, niż wynikałoby to z modelu bez interakcji <code>Eye:Sex</code>, przy uwzględnieniu pozostałych efektów w modelu. Natomiast wartość 1.17 dla kobiet o brązowych oczach wskazuje, że taka kombinacja występuje ponadprzeciętnie (częściej o około 17%) niż wynikałoby to z modelu bez tej interakcji.</p>
<p>Parametry <code>Hair:Eye</code> dotyczą relacji między kolorem włosów a kolorem oczu i nie mają znaczenia dla oceny roli płci w strukturze zależności. Stanowią natomiast wartościowe podsumowanie siły i kierunku powiązań pomiędzy włosami i oczami, pokazując, które kombinacje są nadreprezentowane, a które pojawiają się rzadziej od oczekiwań.</p>
<ol start="8" type="1">
<li>Model testujący czy płeć wnosi jakąś istotną interakcję?</li>
</ol>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Model bez interakcji z płcią:</span></span>
<span><span class="va">m_noSexInt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="va">Freq</span> <span class="op">~</span> <span class="va">Hair</span> <span class="op">*</span> <span class="va">Eye</span> <span class="op">+</span> <span class="va">Sex</span>, data <span class="op">=</span> <span class="va">hec</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_noSexInt</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Formula:
Freq ~ Hair * Eye + Sex
attr(,"variables")
list(Freq, Hair, Eye, Sex)
attr(,"factors")
     Hair Eye Sex Hair:Eye
Freq    0   0   0        0
Hair    1   0   0        1
Eye     0   1   0        1
Sex     0   0   1        0
attr(,"term.labels")
[1] "Hair"     "Eye"      "Sex"      "Hair:Eye"
attr(,"order")
[1] 1 1 1 2
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
&lt;environment: R_GlobalEnv&gt;
attr(,"predvars")
list(Freq, Hair, Eye, Sex)
attr(,"dataClasses")
     Freq      Hair       Eye       Sex 
"numeric"  "factor"  "factor"  "factor" 

Statistics:
                      X^2 df  P(&gt; X^2)
Likelihood Ratio 19.85656 15 0.1775045
Pearson          19.56712 15 0.1891745</code></pre>
</div>
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Porównanie: czy dodanie interakcji z Sex poprawia dopasowanie?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m_noSexInt</span>, <span class="va">m_no3way</span>, test <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>LR tests for hierarchical log-linear models

Model 1:
 Freq ~ Hair * Eye + Sex 
Model 2:
 Freq ~ (Hair + Eye + Sex)^2 

           Deviance df Delta(Dev) Delta(df) P(&gt; Delta(Dev)
Model 1   19.856561 15                                    
Model 2    6.761258  9  13.095303         6        0.04155
Saturated  0.000000  0   6.761258         9        0.66196</code></pre>
</div>
</div>
<p>Model zawierający interakcję między kolorem włosów i kolorem oczu oraz efekty główne wszystkich zmiennych, ale pozbawiony interakcji z płcią, wykazuje dobre dopasowanie do danych. Wysokie wartości p-value obu testów dopasowania wskazują, że różnice między liczebnościami obserwowanymi i oczekiwanymi nie są istotne statystycznie. Oznacza to, że uproszczona struktura modelu jest wystarczająca do odtworzenia układu częstości w tabeli.</p>
<p>Z takiego wyniku wynika, że obecność płci nie wprowadza istotnych modyfikacji zależności między kolorem włosów a kolorem oczu. Sam efekt płci, uwzględniony jako efekt główny, pozwala odtworzyć zmienność liczebności bez konieczności modelowania interakcji z pozostałymi zmiennymi. Strukturę współwystępowania włosów i oczu można więc traktować jako stabilną niezależnie od płci, a różnice pomiędzy poziomami tej zmiennej nie wykraczają poza proste różnice w liczebnościach marginalnych.</p>
<p>Porównanie modeli wskazuje, że dodanie interakcji z płcią (<code>Hair:Sex</code> oraz <code>Eye:Sex</code>) istotnie poprawia dopasowanie w stosunku do modelu, który takiej interakcji nie zawiera. Jednocześnie interakcja trzeciego rzędu pozostaje nieistotna, co oznacza, że płeć wpływa na rozkład włosów i oczu, ale nie modyfikuje zależności między tymi dwiema cechami.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_noSexInt</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Re-fitting to get fitted values</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>, , Sex = Male

       Eye
Hair        Brown      Blue     Hazel     Green
  Black 32.047297  9.425676  7.069257  2.356419
  Brown 56.082770 39.587838 25.449324 13.667230
  Red   12.253378  8.011824  6.597973  6.597973
  Blond  3.298986 44.300676  4.712838  7.540541

, , Sex = Female

       Eye
Hair        Brown      Blue     Hazel     Green
  Black 35.952703 10.574324  7.930743  2.643581
  Brown 62.917230 44.412162 28.550676 15.332770
  Red   13.746622  8.988176  7.402027  7.402027
  Blond  3.701014 49.699324  5.287162  8.459459</code></pre>
</div>
</div>
<p>Wartości <code>fitted(m_noSexInt)</code> przedstawiają liczebności oczekiwane w modelu, który uwzględnia jedynie interakcję <code>Hair:Eye</code>, a płeć traktuje wyłącznie jako efekt główny. Oznacza to, że model dopuszcza różnice w ogólnej liczbie mężczyzn i kobiet, ale zakłada, że <strong>struktura współwystępowania kolorów włosów i oczu jest identyczna w obu płciach</strong>.</p>
<p>W praktyce oznacza to, że różnice pomiędzy tablicami dla mężczyzn i kobiet wynikają wyłącznie z proporcji płci w próbie oraz z rozkładów marginalnych, a nie z tego, że płeć modyfikuje zależność między włosami a oczami. Każdy „kształt” tabeli dla danej płci jest zatem skalowaną wersją tej samej struktury Hair–Eye. Jeśli pewna kombinacja włosów i oczu jest relatywnie częsta u mężczyzn, to model zakłada, że powinna być tak samo relatywnie częsta u kobiet, tylko w innej skali wynikającej z ogólnej liczebności kobiet. Dzięki temu wynik łatwo interpretować jako konsekwencję założenia, że płeć nie zmienia wzorca współwystępowania kolorów włosów i oczu.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Kod</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">m_noSexInt</span><span class="op">$</span><span class="va">param</span><span class="op">$</span><span class="va">Hair.Eye</span><span class="op">)</span></span></code></pre></div><button title="Kopiuj do schowka" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       Eye
Hair       Brown      Blue     Hazel     Green
  Black 2.651732 0.6712141 1.1104285 0.5059628
  Brown 1.318449 0.8009509 1.1357654 0.8337621
  Red   1.056148 0.5943065 1.0795875 1.4757306
  Blond 0.270821 3.1298428 0.7344512 1.6063203</code></pre>
</div>
</div>
<p>Parametry <code>exp(Hair:Eye)</code> pokazują, jak bardzo dana kombinacja koloru włosów i koloru oczu jest nad- lub niedoreprezentowana względem sytuacji niezależności tych cech, po uwzględnieniu efektów głównych. Wartości większe od 1 wskazują na względny nadmiar obserwacji, natomiast wartości mniejsze od 1 oznaczają względny niedobór danej kombinacji w stosunku do oczekiwań modelowych.</p>
<p>Dla czarnych włosów współczynnik równy 2.65 dla brązowych oczu oznacza, że osoby o tej kombinacji pojawiają się w danych ponad dwukrotnie częściej, niż wynikałoby to z niezależnego rozkładu kategorii. Jednocześnie parametr 0.67 dla czarnych włosów i niebieskich oczu wskazuje, że ta kombinacja pojawia się znacznie rzadziej, niż sugerowałby model bez interakcji. Wartość 1.11 dla pary czarne włosy i piwne oczy jest bliska jedności, co oznacza, że liczebność tej kombinacji odpowiada temu, co przewidywałby model niezależności.</p>
<p>Z kolei dla włosów blond bardzo wysoki współczynnik 3.13 przy niebieskich oczach świadczy o silnej nadreprezentacji tej kombinacji w danych. Tymczasem wartość 0.27 przy brązowych oczach oznacza, że osoby o blond włosach i brązowych oczach pojawiają się znacznie rzadziej, niż można by oczekiwać, gdyby włosy i oczy były od siebie niezależne. Analogicznie, parametr 1.61 przy zielonych oczach sygnalizuje umiarkowany nadmiar tej kombinacji dla osób o jasnych włosach. Wartości te pokazują, że zależność między kolorem włosów i oczu ma wyraźny charakter i prowadzi do zróżnicowanych wzorców współwystępowania w różnych parach kategorii.</p>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-goodmanSimultaneousConfidenceIntervals1964" class="csl-entry" role="listitem">
Goodman, Leo A. 1964. <span>„Simultaneous Confidence Intervals for Contrasts Among Multinomial Populations”</span>. <em>The Annals of Mathematical Statistics</em> 35 (2): 716–25. <a href="https://doi.org/10.1214/aoms/1177703569">https://doi.org/10.1214/aoms/1177703569</a>.
</div>
<div id="ref-goodmanAnalysisCrossClassifiedData1968" class="csl-entry" role="listitem">
———. 1968. <span>„The Analysis of Cross-Classified Data: Independence, Quasi-Independence, and Interactions in Contingency Tables with or Without Missing Entries”</span>. <em>Journal of the American Statistical Association</em> 63 (324): 1091–131. <a href="https://doi.org/10.2307/2285873">https://doi.org/10.2307/2285873</a>.
</div>
<div id="ref-goodmanMultivariateAnalysisQualitative1970" class="csl-entry" role="listitem">
———. 1970. <span>„The Multivariate Analysis of Qualitative Data: Interactions among Multiple Classifications”</span>. <em>Journal of the American Statistical Association</em> 65 (329): 226–56. <a href="https://doi.org/10.1080/01621459.1970.10481076">https://doi.org/10.1080/01621459.1970.10481076</a>.
</div>
<div id="ref-goodmanAnalysisMultidimensionalContingency1971" class="csl-entry" role="listitem">
———. 1971. <span>„The Analysis of Multidimensional Contingency Tables: Stepwise Procedures and Direct Estimation Methods for Building Models for Multiple Classifications”</span>. <em>Technometrics</em> 13 (1): 33–61. <a href="https://doi.org/10.1080/00401706.1971.10488753">https://doi.org/10.1080/00401706.1971.10488753</a>.
</div>
<div id="ref-goodmanAssociationModelsBivariate1981" class="csl-entry" role="listitem">
———. 1981. <span>„Association Models and the Bivariate Normal for Contingency Tables with Ordered Categories”</span>. <em>Biometrika</em> 68 (2): 347–55. <a href="https://doi.org/10.2307/2335579">https://doi.org/10.2307/2335579</a>.
</div>
<div id="ref-goodmanMeasuresAssociationCross1954" class="csl-entry" role="listitem">
Goodman, Leo A., i William H. Kruskal. 1954. <span>„Measures of Association for Cross Classifications”</span>. <em>Journal of the American Statistical Association</em> 49 (268): 732–64. <a href="https://doi.org/10.2307/2281536">https://doi.org/10.2307/2281536</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Skopiowano!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Skopiowano!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./correspondence.html" class="pagination-link" aria-label="Analiza korespondencji">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analiza korespondencji</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="Literatura">
        <span class="nav-page-text">Literatura</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Wielowymiarowa analiza danych</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/DariuszMajerek/WAD_new/issues/new" class="toc-action"><i class="bi bi-github"></i>Zgłoś problem</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Dariusz Majerek ©2025</p>
</div>
  </div>
</footer>


</body></html>